name: Build Example
on:
  workflow_dispatch:

jobs:
  idk-man:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.1
    - name: Setup Node.js environment
      uses: actions/setup-node@v6.0.0
    - name: Create zip package
      run: |
        zip -r app.zip . \
          -x ".git/*" \
          -x ".github/*"
    - name: verification
      run: ls -alhR
